// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFeed(arg1) {
  return window['go']['main']['App']['CreateFeed'](arg1);
}

export function CreateNewCollection(arg1) {
  return window['go']['main']['App']['CreateNewCollection'](arg1);
}

export function FetchRSSFeeds() {
  return window['go']['main']['App']['FetchRSSFeeds']();
}

export function FollowFeed(arg1) {
  return window['go']['main']['App']['FollowFeed'](arg1);
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetFeedItem(arg1) {
  return window['go']['main']['App']['GetFeedItem'](arg1);
}

export function GetFeedItems(arg1) {
  return window['go']['main']['App']['GetFeedItems'](arg1);
}

export function GetFeeds(arg1) {
  return window['go']['main']['App']['GetFeeds'](arg1);
}

export function HandleSaveFeedItem(arg1) {
  return window['go']['main']['App']['HandleSaveFeedItem'](arg1);
}

export function SearchForFeed(arg1) {
  return window['go']['main']['App']['SearchForFeed'](arg1);
}

export function StartRSSFetcher(arg1) {
  return window['go']['main']['App']['StartRSSFetcher'](arg1);
}
