// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {serializers} from '../models';
import {handler} from '../models';

export function CreateFeed(arg1:serializers.CreateFeedRequest):Promise<handler.Response>;

export function CreateNewCollection(arg1:string):Promise<handler.Response>;

export function FollowFeed(arg1:serializers.FollowRequest):Promise<handler.Response>;

export function GetCollections():Promise<handler.Response>;

export function GetFeedItem(arg1:serializers.GetFeedItemRequest):Promise<handler.Response>;

export function GetFeedItems(arg1:serializers.GetFeedItemsRequest):Promise<handler.Response>;

export function GetFeeds(arg1:serializers.GetFeedsRequest):Promise<handler.Response>;

export function HandleSaveFeedItem(arg1:serializers.HandleSaveFeedItemRequest):Promise<handler.Response>;

export function SearchForFeed(arg1:string):Promise<handler.Response>;

export function SetFeedItemAsRead(arg1:number):Promise<handler.Response>;
