// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {time} from '../models';

export function CreateFeed(arg1:main.CreateFeedRequest):Promise<main.Response>;

export function CreateNewCollection(arg1:string):Promise<main.Response>;

export function FetchRSSFeeds():Promise<void>;

export function FollowFeed(arg1:main.FollowRequest):Promise<main.Response>;

export function GetCollections():Promise<main.Response>;

export function GetFeedItem(arg1:main.GetFeedItemRequest):Promise<main.Response>;

export function GetFeedItems(arg1:main.GetFeedItemsRequest):Promise<main.Response>;

export function GetFeeds(arg1:main.GetFeedsRequest):Promise<main.Response>;

export function HandleSaveFeedItem(arg1:main.HandleSaveFeedItemRequest):Promise<main.Response>;

export function SearchForFeed(arg1:string):Promise<main.Response>;

export function SetFeedItemAsRead(arg1:number):Promise<main.Response>;

export function StartRSSFetcher(arg1:time.Duration):Promise<void>;
